🐛fix: lookup cookie in response header
gofiber/fiber pull request #1191
Opened 2021-02-27 14:41 UTC by tianjipeng

**Please provide enough information so that others can review your pull request:**

This pr try to fix this issue: https://github.com/gofiber/fiber/issues/1184

**Explain the *details* for making this change. What existing problem does the pull request solve?**

``ctx.Cookies`` will look up coookie in response header if cookie is not found in request header

**Commit formatting** 

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

2021-02-27 15:15 UTC, ReneWerner87 requested changes
Please don't change the cookie method, but the content of the session manager and please consider the fresh status like in my comments in the issue, otherwise the session will be marked as not new in the second handler, although it didn't exist before the request start

2021-02-28 12:25 UTC, tianjipeng commented
@ReneWerner87 Sorry, my mistake.  Now it is updated, please review it again, thanks.

2021-02-28 12:36 UTC, ReneWerner87 commented
Look better now, will check it again on my pc in a few hours.

2021-02-28 16:31 UTC, ReneWerner87 approved these changes

2021-03-01 16:25 UTC, merged