feat: expiration per session
gofiber/fiber pull request #1363
Opened 2021-06-03 19:22 UTC by mirusky

Please provide enough information so that others can review your pull request:

Added a sess.ExpiresIn() method who set a custom expiration for a session.

Explain the details for making this change. What existing problem does the pull request solve?

Related to #1298 , for short, sess.ExpiresIn() use a custom session expiration insted of default value.

2021-06-03 20:01 UTC, hi019 requested changes
Thanks for the PR. Did a small review from my phone, I'll take a closer look later today

2021-06-06 18:38 UTC, mlukasik-dev commented on middleware/session/session.go
> +func (s *Session) ExpiresIn(exp time.Duration) {
And I'd better change comment to:  
`// ExpiresIn sets a specific expiration for this session` (grammatical mistake)

2021-06-10 05:05 UTC, tomaswarynyca commented on middleware/session/session.go
> +func (s *Session) ExpiresIn(exp time.Duration) {
@mirusky  could you generate the commit with the modifications?

2021-06-11 06:34 UTC, ReneWerner87 commented
@mirusky can you look over the review notes again and adjust accordingly so i can merge at some point

2021-06-12 14:59 UTC, mirusky commented
Hey @ReneWerner87 @tomaswarynyca I did the changes, sorry for delay I was too busy.

2021-06-13 10:38 UTC, ReneWerner87 approved these changes

2021-06-13 10:39 UTC, merged