🔥 Feature: add cache header to show cache status
gofiber/fiber pull request #1368
Opened 2021-06-06 12:07 UTC by WLun001

**Please provide enough information so that others can review your pull request:**
Cache middleware to returns `S-Cache` header to show cache status, `hit`, `miss` or `unreachable`

Not using `X-Cache` because I think some CDN uses this value?

2021-06-06 14:25 UTC, hi019 requested changes

2021-06-06 14:25 UTC, hi019 commented on middleware/cache/README.md
> +	CacheHeader:  "S-Cache",
The default header should be X-Cache, it's used by many other CDN's and X indicates a non standard header

2021-06-06 14:30 UTC, hi019 commented
Thanks for the PR, can you also add tests?

2021-06-08 21:11 UTC, ReneWerner87 approved these changes

2021-06-12 03:09 UTC, hi019 commented on middleware/cache/cache_test.go
> +	utils.AssertEqual(t, "miss", resp.Header.Get("X-Cache"))
Should be able to use the cache status constants in these tests

2021-06-13 08:52 UTC, merged