add tls config for http client in proxy middleware
gofiber/fiber pull request #1393
Opened 2021-06-19 08:59 UTC by tuhao1020

In some cases, we often need to disable certificate validation, so I add `WithTlsConfig` function for proxy.
This function can be used before `Forward`, for example:
```
proxy.WithTlsConfig(tls.Config{
    InsecureSkipVerify: true,
})
```

2021-06-19 13:45 UTC, ReneWerner87 commented
Thx, could you add a description/example here  https://github.com/gofiber/fiber/blob/master/middleware/proxy/README.md and a test

2021-06-20 04:44 UTC, tuhao1020 commented
@ReneWerner87 example updated. but I don't know how to write a test that mock a https server and use a self-signed certificate 😿

2021-06-20 06:57 UTC, ReneWerner87 commented
please check 
https://github.com/gofiber/fiber/blob/master/app_test.go#L971
https://github.com/gofiber/fiber/blob/master/app_test.go#L988
https://github.com/gofiber/fiber/blob/master/app_test.go#L1022
https://github.com/gofiber/fiber/blob/master/client_test.go#L909

we have already deposited a test certificate which you can use, please have a look at the tests, think you can come up with an idea, you can also do it like with the client agent test

2021-06-20 12:46 UTC, tuhao1020 commented
@ReneWerner87 test added, please have a check.

2021-06-20 15:04 UTC, ReneWerner87 approved these changes

2021-06-20 19:01 UTC, ReneWerner87 commented
Could you check the unittests again, there is an error and maybe its related to the test code changes.

2021-06-21 01:26 UTC, tuhao1020 commented
```
=== CONT  Test_Proxy_Timeout_Slow_Server
--- PASS: Test_Proxy_Forward_WithTlsConfig (10.64s)
==================
WARNING: DATA RACE
Read at 0x0000011c3b08 by goroutine 13:
  github.com/gofiber/fiber/v2/middleware/proxy.Balancer()
      D:/a/fiber/fiber/middleware/proxy/proxy.go:50 +0x5d6
  github.com/gofiber/fiber/v2/middleware/proxy.Test_Proxy_Modify_Request()
      D:/a/fiber/fiber/middleware/proxy/proxy_test.go:179 +0x1a2
  testing.tRunner()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1050 +0x1f2

Previous write at 0x0000011c3b08 by goroutine 11:
  [failed to restore the stack]

Goroutine 13 (running) created at:
  testing.(*T).Run()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1095 +0x53e
  testing.runTests.func1()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1339 +0xad
  testing.tRunner()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1050 +0x1f2
  testing.runTests()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1337 +0x59b
  testing.(*M).Run()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1252 +0x306
  main.main()
      _testmain.go:62 +0x22a

Goroutine 11 (finished) created at:
  testing.(*T).Run()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1095 +0x53e
  testing.runTests.func1()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1339 +0xad
  testing.tRunner()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1050 +0x1f2
  testing.runTests()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1337 +0x59b
  testing.(*M).Run()
      C:/hostedtoolcache/windows/go/1.14.15/x64/src/testing/testing.go:1252 +0x306
  main.main()
      _testmain.go:62 +0x22a
==================
=== CONT  Test_Proxy_Modify_Request
Error:     testing.go:965: race detected during execution of test
--- FAIL: Test_Proxy_Modify_Request (2.00s)
=== CONT  Test_Proxy_Timeout_Slow_Server
Error:     testing.go:965: race detected during execution of test
--- FAIL: Test_Proxy_Timeout_Slow_Server (4.00s)
```

@ReneWerner87 Does it mean clientTlsConfig should be protected by a mutex? But they're all ok in my local test environment.

2021-06-21 06:53 UTC, ReneWerner87 commented
will also analyze it again, give me a little time, don't know if i will make it today

2021-06-23 07:13 UTC, ReneWerner87 requested changes
the code looks good, i just noticed that you set this tls config global and it is only present once

for the client that does the DO and FORWARD without further settings this is completely ok

but with the other variant of the BALANCER or with the NEW method this is not ok, because this middleware could be used multiple times for different routes, i would also expect that it can behave differently in these, i.e. the tls configuration would have to be injected via the config

sorry for the late comment, can you extend the config and possibly the test, so that it tests both cases, the DO/FORWARD and the Balancer

2021-06-23 17:33 UTC, tuhao1020 commented
@ReneWerner87 Thanks!  
tls config has been moved from the global configuration to `proxy.Config` and `proxy.WithTlsConfig` is reserved for `proxy.Forward`. I have run `go test` in my laptop and passed all test.

2021-06-24 06:13 UTC, ReneWerner87 approved these changes

2021-06-24 06:13 UTC, merged