✨feature: Pass all locals to ctx.Render
gofiber/fiber pull request #1693
Opened 2022-01-07 17:13 UTC by kingdevnl

**✨feature: Pass all locals to ctx.Render**

This will by default pass all locals set user ctx.Local to the Template engine.

This could be usefull for setting variables using a middleware.

2022-01-07 17:17 UTC, ReneWerner87 reviewed
Please add a testcase and something in the documentation (https://github.com/gofiber/docs)

2022-01-07 21:01 UTC, ReneWerner87 approved these changes

2022-01-08 17:19 UTC, hi019 requested changes

2022-01-08 17:19 UTC, hi019 commented on app.go
> +	// PassLocalsToViews Enables passing of the locals set on a fiber.Ctx to the template engine
We should probably mention that the Locals will be accessible to the template just like any other passed value, and that they will overwrite keys manually passed to `Render`.

2022-01-09 21:42 UTC, ReneWerner87 requested changes

2022-01-09 21:42 UTC, ReneWerner87 commented on ctx.go
> +				bindMap[string(key)] = val
the map that is being handed in should only be expanded, not completely replaced

furthermore the values which are given directly to the render function should have more value

i.e. a value which is in the locals with key "abc" and one which is directly passed to the render function, the one which is passed to the render function should win

2022-01-10 08:06 UTC, ReneWerner87 commented on ctx.go
> +				bindMap[string(key)] = val
@kingdevnl

2022-01-21 08:20 UTC, ReneWerner87 commented
@kingdevnl

2022-01-21 09:03 UTC, kingdevnl commented
Will have a look once I'm home, had quite a busy week so wasn't able to check it before

2022-01-21 09:04 UTC, ReneWerner87 commented
thx

2022-01-24 07:28 UTC, ReneWerner87 approved these changes

2022-01-24 07:29 UTC, merged