🩹 Fix limiter middleware db connection
gofiber/fiber pull request #1813
Opened 2022-03-07 18:09 UTC by qracer

Closes #1812

This PR just removes `release` method from [manager.go](https://github.com/gofiber/fiber/blob/master/middleware/limiter/manager.go) so `SkipSuccessfulRequests` and `SkipFailedRequests` from the limiter config will work properly.

Close my PR if you find my approach inappropriate to merge. I just used the simplest way to fix the bug but it can be fixed via refactoring code in [limited_config.go](https://github.com/gofiber/fiber/blob/master/middleware/limiter/limiter_fixed.go)

2022-03-10 07:36 UTC, ReneWerner87 commented
i will check this tomorrow

2022-03-11 22:12 UTC, ReneWerner87 commented
@qracer I think releasing the memory and putting it back into the pool is important for the performance.

You are right, if another storage is used, the following construct makes no sense

I think we should execute the get on the key  in the body of the block and set it again after the change, then the releasing can also remain in it.

Should work or?

2022-03-12 08:49 UTC, qracer commented
@ReneWerner87 I reckon we can do without calling `get` twice. A more convenient solution would be to rearrange the mutex schedule and postpone `set` execution with `defer`. I will commit a new bugfix this evening.

2022-03-12 09:51 UTC, ReneWerner87 commented
Ok.

Thought one the position is binding, because one has only after the next the results.
I'm curious how your fix looks like.
Best would also be more advanced tests that test just that.

2022-03-12 17:44 UTC, qracer commented
@ReneWerner87 I've updated the pull request and changed the bugfix approach. Sorry for no test, I don't know  how to mock every available database efficiently to test

2022-03-12 20:54 UTC, ReneWerner87 commented
Ok, no problem

2022-03-14 07:40 UTC, ReneWerner87 requested changes

2022-03-14 07:40 UTC, ReneWerner87 commented on middleware/limiter/limiter_fixed.go
> -		manager.set(key, e, cfg.Expiration)
think moving the set function must also be done in the part where the limit was reached

2022-03-14 07:40 UTC, ReneWerner87 commented on middleware/limiter/limiter_fixed.go
> +			mux.Unlock()
this is not a good idea, the mutex in the defer would block the reading for too long

Because with c.Next() all possible handlers are executed

2022-03-14 17:49 UTC, ReneWerner87 commented
@qracer i added some comments, can you please check it again

2022-03-15 06:51 UTC, ReneWerner87 approved these changes

2022-03-15 11:28 UTC, ReneWerner87 approved these changes

2022-03-15 11:41 UTC, merged