Improved proxy.DomainForward method
gofiber/fiber pull request #2326
Opened 2023-02-04 02:41 UTC by ryanbekhen

## Description

I want to patch proxy.DomainForward which only works on one domain.

Case:
```go
app.Use(proxy.DomainForward("a.example.com", "http://localhost:3000")
app.Use(proxy.DomainForward("b.example.com", "http://localhost:4000")
```
a.example.com will not work and only b.example.com will work.

Problem Solving:
i made it easier as below.

```go
app.Use(DomainForward(map[string]string{
  "a.example.com":  "http://localhost:3000",
  "b.example.com":  "http://localhost:4000",
}))
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - https://github.com/gofiber/docs for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

2023-02-04 06:14 UTC, ryanbekhen commented
@ReneWerner87 please review later.

2023-02-04 06:44 UTC, ReneWerner87 commented
But this is a breaking change
We have to think before we design exposed methods for the library

2023-02-04 07:06 UTC, ryanbekhen commented
@ReneWerner87 so what should I do if the PR labeled `Breaking Change`.

2023-02-04 07:11 UTC, ReneWerner87 commented
We can not accept the improvent in v2
One possibility would be to try to make it backward compatible

2023-02-04 07:20 UTC, ryanbekhen commented
@ReneWerner87  please look at commit  14cf4b67366b4092de80f688c5dd4da7a08dbacf, I just changed the way to use DomainForward so I can add domains. Does this include Breaking change?

2023-02-04 07:24 UTC, ReneWerner87 commented
The first parameter of DomainForward is a complete different datatype
This is a breaking change, without compatibility to the usage before

2023-02-04 07:29 UTC, ryanbekhen commented
@ReneWerner87  Ok thanks for the info. Does this mean it will be merged in the next minor version?

2023-02-04 07:34 UTC, ReneWerner87 commented
This means that we will be able to adjust it in the next major version at the earliest.

This will probably come out in a few months

2023-02-04 07:36 UTC, ryanbekhen commented
@ReneWerner87 maybe I can just add documentation when using multiple domains.

2023-02-04 07:50 UTC, ReneWerner87 commented
Ok, documentation changes are okay

2023-02-04 08:12 UTC, ryanbekhen commented
ok I will add the documentation later

2023-02-05 14:04 UTC, efectn commented
@ryanbekhen can you create/edit a PR that targets v3 branch. I think this is nice change for v3.

2023-02-06 02:44 UTC, ryanbekhen commented
@efectn Yes, I can.  So, when can I add this feature?

2023-02-06 04:48 UTC, efectn commented
> @efectn Yes, I can. So, when can I add this feature?

When you want. I merged master into the v3 beta branch

2023-02-06 06:19 UTC, ryanbekhen commented
@efectn Previously I added 2 features, namely proxy.DomainForward and proxy.BalancerForward. Do I add these two features to v3 or only proxy.DomainForward?

2023-02-06 06:27 UTC, efectn commented
> @efectn Previously I added 2 features, namely proxy.DomainForward and proxy.BalancerForward. Do I add these two features to v3 or only proxy.DomainForward?

They are already exists on v3-beta -> https://github.com/gofiber/fiber/blob/v3-beta/middleware/proxy/proxy.go#L176

2023-02-06 06:43 UTC, ryanbekhen commented
@efectn I have changed the target branch to v3-beta

2023-02-06 06:53 UTC, efectn requested changes
There are some linting errors that unrelated to this PR. I'll fix them later.

2023-02-06 06:53 UTC, efectn commented on middleware/proxy/proxy.go
> +	return func(c *fiber.Ctx) error {
Remove the pointer here

2023-02-06 06:53 UTC, efectn commented on middleware/proxy/proxy_test.go
> +	_, addr1 := createProxyTestServer(t, func(c *fiber.Ctx) error {
Here too

2023-02-06 06:53 UTC, efectn commented on middleware/proxy/proxy_test.go
> +	_, addr2 := createProxyTestServer(t, func(c *fiber.Ctx) error {
Here

2023-02-06 06:53 UTC, efectn commented on middleware/proxy/proxy_test.go
> +	utils.AssertEqual(t, nil, err2)
Change assertequals with require

2023-02-06 06:53 UTC, efectn commented
@ryanbekhen can you check my last comments

2023-02-06 06:58 UTC, ryanbekhen commented
@efectn i have changed assertequals to require in last commit

2023-02-06 07:20 UTC, efectn approved these changes

2023-02-06 15:10 UTC, ryanbekhen commented
@efectn I'm going to update the readme on the proxy as the signature section hasn't been updated yet.

2023-02-07 09:59 UTC, efectn approved these changes

2023-08-05 19:02 UTC, merged