feat: add ability to print custom message on startup
gofiber/fiber pull request #2491
Opened 2023-06-02 09:32 UTC by Saman-Safaei

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 
Explain the *details* for making this change. What existing problem does the pull request solve?

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [ ] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

2023-06-02 09:51 UTC, efectn commented
I think it's better idea to improve onListen hook instead of adding new config

2023-06-02 13:07 UTC, gaby commented
> I think it's better idea to improve onListen hook instead of adding new config

Agree

2023-06-02 13:08 UTC, cmd777 commented
> I think it's better idea to improve onListen hook instead of adding new config

@efectn So, something like this? (this is just a mock-up, and does not take prefork into account)

```go
func (app *App) SetStartupMessage(fun ...func() error) {
	// disable default startup message
	app.config.DisableStartupMessage = true

	// add each func to the onListen hook
	app.hooks.onListen = append(app.hooks.onListen, fun...)
}
```
and it allows for this:

```go
app := fiber.New()

app.SetStartupMessage(
	func() error {
		log.Println("Hello, ")
		return nil
	}, func() error {
		log.Println("World!")
		return nil
	},
)

log.Fatal(app.Listen(":9090"))

2023/06/02 15:03:13 Hello, 
2023/06/02 15:03:13 World!
^Csignal: interrupt
```

2023-06-02 16:15 UTC, efectn commented
> > I think it's better idea to improve onListen hook instead of adding new config
> 
> @efectn So, something like this? (this is just a mock-up, and does not take prefork into account)
> 
> ```go
> func (app *App) SetStartupMessage(fun ...func() error) {
> 	// disable default startup message
> 	app.config.DisableStartupMessage = true
> 
> 	// add each func to the onListen hook
> 	app.hooks.onListen = append(app.hooks.onListen, fun...)
> }
> ```
> 
> and it allows for this:
> 
> ```go
> app := fiber.New()
> 
> app.SetStartupMessage(
> 	func() error {
> 		log.Println("Hello, ")
> 		return nil
> 	}, func() error {
> 		log.Println("World!")
> 		return nil
> 	},
> )
> 
> log.Fatal(app.Listen(":9090"))
> 
> 2023/06/02 15:03:13 Hello, 
> 2023/06/02 15:03:13 World!
> ^Csignal: interrupt
> ```



> > I think it's better idea to improve onListen hook instead of adding new config
> 
> @efectn So, something like this? (this is just a mock-up, and does not take prefork into account)
> 
> ```go
> func (app *App) SetStartupMessage(fun ...func() error) {
> 	// disable default startup message
> 	app.config.DisableStartupMessage = true
> 
> 	// add each func to the onListen hook
> 	app.hooks.onListen = append(app.hooks.onListen, fun...)
> }
> ```
> 
> and it allows for this:
> 
> ```go
> app := fiber.New()
> 
> app.SetStartupMessage(
> 	func() error {
> 		log.Println("Hello, ")
> 		return nil
> 	}, func() error {
> 		log.Println("World!")
> 		return nil
> 	},
> )
> 
> log.Fatal(app.Listen(":9090"))
> 
> 2023/06/02 15:03:13 Hello, 
> 2023/06/02 15:03:13 World!
> ^Csignal: interrupt
> ```

Hooks handlers accept parameters as you can see here https://github.com/gofiber/fiber/blob/master/hooks.go#L8

We can pass needed variables to hook like this. However, it'll break handler signature. Perhaps we put them into a struct and pass it as variadic, so it won't break compatibility

2023-06-09 20:43 UTC, efectn commented
I'd recommend something like this:

```go
type ListenData struct {
	Host string
	Port string
	TLS  string
}

app.Hooks().OnListen(func(data ...ListenData) error {
	if fiber.IsChild() {
		return nil
	}

	fmt.Print(data[0].Host)

	return nil
})
```

2023-06-12 05:55 UTC, ReneWerner87 commented on app.go
> +	if err := app.hooks.executeOnListenHooks(listenData...); err != nil {
pls use the new function 
runOnListenHooks for this

2023-06-12 05:56 UTC, ReneWerner87 requested changes
check my hint

2023-06-12 14:52 UTC, Saman-Safaei commented
> check my hint

I fixed that

2023-06-13 10:26 UTC, cmd777 requested changes

2023-06-13 10:26 UTC, cmd777 commented on docs/guide/hooks.md
>    fiber.IsChild()
this is missing an !if (assuming you want to print once)

2023-06-13 10:26 UTC, cmd777 commented on docs/guide/hooks.md
>    fmt.Println(listenData.TLS + "://" + listenData.Host + ":" + listenData.Port)
This is just preference, but should use log.Println instead

2023-06-13 19:35 UTC, cmd777 commented on docs/guide/hooks.md
> +  if (fiber.IsChild()) {
Does work, but normally gets shortened to
```suggestion
  if fiber.IsChild() {
```
if you use VSCode or similar

2023-06-13 19:37 UTC, cmd777 requested changes
Can you take a look at the new linter warnings/errors?

2023-06-13 19:37 UTC, cmd777 commented on listen.go
> +func (app *App) prepareListenData(addr string, isTls bool) ListenData {
Can you fix this linter warning?

2023-06-13 19:37 UTC, cmd777 commented on listen.go
> +func (app *App) startupMessage(addr string, isTls bool, pids string) { //nolint: revive // Accepting a bool param is fine here
And this as well

2023-06-14 05:27 UTC, cmd777 requested changes
Please revert the [f98133f](https://github.com/gofiber/fiber/pull/2491/commits/f98133f5755a8a6df70bf75e821a19b932669d33) commit.
While the go.mod does specify `go 1.20`, [tests still run with go 1.17-1.20](https://github.com/gofiber/fiber/blob/master/.github/workflows/test.yml#L20), and 1.17 does not contain `any` yet.

2023-06-14 08:40 UTC, cmd777 approved these changes

2023-06-14 09:47 UTC, efectn commented
@Saman-Safaei can you add nolint flag for a method that isTLS param is used. 

You can check other nolint flag usages for an example

2023-06-19 09:57 UTC, ReneWerner87 approved these changes

2023-06-19 10:35 UTC, efectn approved these changes

2023-06-19 11:11 UTC, merged