✨ Adds End method to context
gofiber/fiber pull request #2586
Opened 2023-08-17 22:55 UTC by scandar

## Description
Adds end method to the context [similar to express](https://expressjs.com/en/5x/api.html#res.end)
It's an alias for `c.Send(nil)`
Fixes #2582

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [x] For new code I have written benchmarks so that they can be analyzed and improved

2023-08-17 23:07 UTC, efectn approved these changes

2023-08-17 23:08 UTC, gaby approved these changes
Lgtm

2023-08-18 05:47 UTC, ReneWerner87 requested changes
Small change needed

2023-08-18 05:47 UTC, ReneWerner87 commented on docs/api/ctx.md
> +## End
Pls put it in the alphabetical order in the list of methods

2023-08-18 06:12 UTC, ReneWerner87 commented
@scandar 
```ts
const express = require('express');
const app = express();

app.get('/', (req, res) => {
  // Setting data in the response body
  res.write('Hello, ');
  res.write('World!');

  // Sending the response
  res.end();
});

app.listen(3000, () => {
  console.log('Server is listening on port 3000');
});
```
I think this is not possible or ?
how to reset the body completely and not just send it on

but i think the end method is just to say that the response can go off and not to reset everything

2023-08-18 09:33 UTC, scandar commented
@ReneWerner87 I believe it should override the body to `nil`
this is from [the express docs ](https://expressjs.com/en/5x/api.html#res.end)

> Ends the response process. This method actually comes from Node core, specifically the [response.end() method of http.ServerResponse](https://nodejs.org/api/http.html#http_response_end_data_encoding_callback).
> Use to quickly end the response without any data. If you need to respond with data, instead use methods such as [res.send()](https://expressjs.com/en/5x/api.html#res.send) and [res.json()](https://expressjs.com/en/5x/api.html#res.json).

2023-08-18 11:08 UTC, ReneWerner87 commented
![image](https://github.com/gofiber/fiber/assets/7063188/0fe8c066-8fac-45ba-9aa3-2d868d46c247)
https://nodejs.org/api/http.html#http_response_end_data_encoding_callback

if you pass data to the nodejs end method, the following happens internally
![image](https://github.com/gofiber/fiber/assets/7063188/d2b6168f-5c9a-4892-8c45-bc9c69b000a1)
that means it is used write and then end internally
for us this means that everything that was set before is simply terminated with end, without emptying it

i also saw examples for the write+end case 
https://github.com/nodejs/node/blob/c021b27221dbf65ea23a570d9df91bfdac4b3196/benchmark/http/end-vs-write-end.js#L36-L43

https://nodejs.org/de/docs/guides/anatomy-of-an-http-transaction#sending-response-body
![image](https://github.com/gofiber/fiber/assets/7063188/585e467d-19fe-4575-bfef-911ea1c9e18a)

2023-08-18 11:09 UTC, ReneWerner87 commented
that means we are not allowed to do a body reset, just send it off

2023-08-18 14:04 UTC, mattcarlotta commented
@scandar Perhaps an alternative to using `.Send(nil)` would be to simply return `nil`? 
```go
func (c *Ctx) End() error {
    return nil
}
```
After reviewing the fasthttp internals, having an `.End` method wouldn't accomplish much since it doesn't include a concrete way to flush and end a Response. However it might be nicer to have a chainable End method that can be returned.

For example, currently we need to write something like this if the func returns an error:
```go
func Example(c *fiber.Ctx) error {
    // return c.Status(fiber.StatusOK).Send(nil)

    c.Status(fiber.StatusOK)
    return nil
}
```
Instead, using the code mentioned previously, the `return nil` can be chained to the context:
```go
func Example(c *fiber.Ctx) error {
    return c.Status(fiber.StatusOK).End()
}
```

2023-08-18 14:25 UTC, ReneWerner87 commented
I think we have no way to explicitly trigger the content of the response to be flushed

fasthttp does this in the server flow for the request/response

for this you then create a writer for the connection and flush the content from the response to it

so end can't make the flow actually really end

2023-08-18 18:16 UTC, closed without merging