:sparkles: add feature parse content-type application/x-ndjson
gofiber/fiber pull request #2645
Opened 2023-09-25 11:09 UTC by huykn

## Description

add feature parse content-type application/x-ndjson
ex input body json
```json
{"name":"john"}
{"name":"doe"}
```
expect return array via call method BodyParser

```go
type Demo struct {
    Name string `json:"name" xml:"name" form:"name" query:"name"`
}
c.Request().Header.SetContentType(MIMEApplicationXNDJSON)
c.Request().SetBody([]byte("{\"name\":\"john\"}\n{\"name\":\"doe\"}\n"))
c.Request().Header.SetContentLength(len(c.Body()))
var out []Demo
utils.AssertEqual(t, nil, c.BodyParser(&out))
utils.AssertEqual(t, 2, len(out))
utils.AssertEqual(t, "john", out[0].Name)
utils.AssertEqual(t, "doe", out[1].Name)
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] For new functionalities I follow the inspiration of the express js framework and built them similar in usage
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation - /docs/ directory for https://docs.gofiber.io/
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] If new dependencies exist, I have checked that they are really necessary and agreed with the maintainers/community (we want to have as few dependencies as possible)
- [x] I tried to make my code as fast as possible with as few allocations as possible
- [ ] For new code I have written benchmarks so that they can be analyzed and improved

## Commit formatting:

Use emojis on commit messages so it provides an easy way of identifying the purpose or intention of a commit. Check out the emoji cheatsheet here: https://gitmoji.carloscuesta.me/

2023-09-25 12:59 UTC, efectn requested changes

2023-09-25 12:59 UTC, efectn commented on ctx.go
> +		k := string(key)
please use c.app.getString here

2023-09-25 15:22 UTC, huykn commented on ctx.go
> +		k := string(key)
ok bro

2023-09-26 12:06 UTC, ReneWerner87 commented
thanks for the feature

but i'm not sure if we should support any kind of body parsing as a framework or if it's better to use extension packages for it and focus on the general ones
![image](https://github.com/gofiber/fiber/assets/7063188/224e828d-2e97-42f0-9047-e2bfe70f5895)

@efectn @gaby whats your opinion

2023-09-26 14:46 UTC, gaby commented
@ReneWerner87 I feel like this should be something in `fasthttp` instead of GoFiber. It doesn't make sense to add all this custom logic to the framework `ndjson` is very useful, specially when dealing with processing logs/metrics. Is there a library that could help with this?

2023-09-26 15:00 UTC, efectn commented
> thanks for the feature
> 
> but i'm not sure if we should support any kind of body parsing as a framework or if it's better to use extension packages for it and focus on the general ones ![image](https://user-images.githubusercontent.com/7063188/270648700-224e828d-2e97-42f0-9047-e2bfe70f5895.png)
> 
> @efectn @gaby whats your opinion

I do agree. If we try to implement every JSON implementations, the core will get really bloated.

2023-09-26 15:15 UTC, ReneWerner87 commented
cool would be a plugin system

where we could declare a parser for the content type in a map, then you could add these parsers separately and only the core parsers are included 

app.bodyParser["application/x-www-form-urlencoded"] = formDataParserClosure
app.bodyParser["multipart/form-data"] = multiformDataParserClosure
app.bodyParser["application/json"] = jsonParserClosure
app.bodyParser["application/xml>"] = xmlParserClosure
app.bodyParser["text/xml"] = xmlParserClosure
....

like express with the bodyParser

2023-09-26 22:03 UTC, gaby commented
@huykn @ReneWerner87 @efectn According to this article you can already parse ndjson using native Go. 

https://abhinavg.net/2020/07/02/parse-ndjson/

```go
decoder := json.NewDecoder(src)
for decoder.More() {
    var order Order
    if err := decoder.Decode(&order); err != nil {
        return fmt.Errorf("parse order: %w", err)
    }

    fmt.Println(order)
}
```

2023-09-27 03:21 UTC, huykn commented
> @huykn @ReneWerner87 @efectn According to this article you can already parse ndjson using native Go.
> 
> https://abhinavg.net/2020/07/02/parse-ndjson/
> 
> ```go
> decoder := json.NewDecoder(src)
> for decoder.More() {
>     var order Order
>     if err := decoder.Decode(&order); err != nil {
>         return fmt.Errorf("parse order: %w", err)
>     }
> 
>     fmt.Println(order)
> }
> ```

@gaby i think we have custom config apply for use 3rd json at: https://github.com/gofiber/fiber/blob/master/docs/guide/faster-fiber.md
if we use only json from encoding/json i think logic is not correct. i'm not sure any json 3rd support ndjson.

2023-09-27 04:32 UTC, ReneWerner87 commented
I tested this and it was not working

2023-09-27 04:48 UTC, huykn commented
> I tested this and it was not working

for feature in this merge request or smt?

2023-09-27 06:02 UTC, ReneWerner87 commented
Feature is working
I mean i tested the parsing of the njson content with the default parser(without extra logic) and that's not working

2023-09-27 07:07 UTC, huykn commented
> Feature is working I mean i tested the parsing of the njson content with the default parser(without extra logic) and that's not working

do you think this feature should be merged or not? or do we need to change to add parsers separately and only the core parsers are included?

2023-09-27 07:33 UTC, ReneWerner87 commented
Good question, we will discuss it and then decide (unfortunately not everyone is here right now)

2023-11-24 05:36 UTC, skydiver1980 approved these changes

2023-12-22 14:31 UTC, ReneWerner87 commented
sorry for the late reply
we have decided not to adopt this feature request

because we can't possibly have parsers in the core for all content types that exist
we currently only want to provide the most common ones in the core 

in v3 we can try to find a way to add parser from outside and in the code we can have a default parser for this in a separate folder or through additional packages from the contrib package

or we add functionality externally that makes it easier to write custom parsing externally

you are welcome to support us in v3 with a proposal

2023-12-22 14:31 UTC, closed without merging