📚 [Doc] fix incorrect status code source
gofiber/fiber pull request #2667
Opened 2023-10-08 02:33 UTC by joshlarsen

## Description

Documentation for status codes (e.g. `fiber.StatusOK`) mentions that status codes in `helpers.go` were copied from [https://github.com/nginx/nginx/blob/67d2a9541826ecd5db97d604f23460210fd3e517/conf/mime.types](https://github.com/nginx/nginx/blob/67d2a9541826ecd5db97d604f23460210fd3e517/conf/mime.types). However, this source contains nothing about HTTP status codes.

This is most likely a typo, as the status codes appear to be copied from net/http, with two small updates. This PR updates the comment to reflect an accurate source for HTTP status codes.

## Type of change

- [x] Bug fix - documentation

2023-10-08 08:21 UTC, ReneWerner87 requested changes
Thx, but the text is duplicated

2023-10-08 09:36 UTC, joshlarsen reviewed
🤦🏼‍♂️

2023-10-10 03:24 UTC, gaby approved these changes

2023-10-10 06:10 UTC, ReneWerner87 approved these changes

2023-10-10 06:11 UTC, merged