Fix nil pointer dereference with Must Bind binding error
gofiber/fiber pull request #3171
Opened 2024-10-17 20:55 UTC by ItsMeSamey

if err is nil err.Error() panics
(eg. c.Bind().Must().JSON(...) successfully binds but panics

2024-10-18 00:29 UTC, gaby commented
@ItsMeSamey Anyway we could trigger this in a new unit-test?

2024-10-18 08:33 UTC, ItsMeSamey commented
@gaby I've added a test for this

2024-10-18 12:48 UTC, gaby requested changes

2024-10-18 12:48 UTC, gaby commented on bind.go
> +	if err == nil || b.should {
This should be && not ||

2024-10-20 09:27 UTC, ItsMeSamey commented
@gaby
I've been wondering why is `Must()` even needed, it only adds overhead so won't we be better off removing it altogether. Setting status should be user's job anyway
Should i open a discussion / issue about this?

2024-10-21 01:02 UTC, gaby commented
> @gaby I've been wondering why is `Must()` even needed, it only adds overhead so won't we be better off removing it altogether. Setting status should be user's job anyway Should i open a discussion / issue about this?

That's a question for @efectn

2024-10-24 06:11 UTC, ReneWerner87 commented
we will discuss this again internally and then let you know which way we want to go, thank you for your work and help

2024-10-24 12:51 UTC, ReneWerner87 commented
here the last statement
https://github.com/gofiber/fiber/pull/3178#issuecomment-2435208194

we want to rename the feature so that there is no confusion with the golang concept of MUST for panics

because the methods always return an error
the feature only ensures that the response is filled with it

2024-10-24 13:25 UTC, ReneWerner87 commented
give us a little time, we are currently discussing what this could look like
whether a config or the method should be renamed and where this can be found

2024-11-15 08:07 UTC, ReneWerner87 commented
@ItsMeSamey sorry for the wait

we have decided to change the `Must` method to `WithAutoHandling

by default no errors should be added to the response, only if someone calls this additional method

can you integrate this into your PR ? and extend/customize the markdown


btw benchmark error is a false positive because of the same named benchmarks
https://github.com/benchmark-action/github-action-benchmark/issues/264

2024-11-16 08:04 UTC, efectn commented on bind.go
> +// If you want to handle binder errors automatically, you can use WithAutoHandling.
Maybe we can rename Should to WithoutAutoHandling()

2024-11-21 11:38 UTC, efectn commented on bind.go
> +// If you want to handle binder errors automatically, you can use WithAutoHandling.
What do you think @gaby @ReneWerner87

2024-11-21 16:58 UTC, efectn commented on bind.go
> +	dontHandle bool
dontHandleErrs would be better

2024-11-21 22:59 UTC, efectn approved these changes

2024-11-21 23:11 UTC, ReneWerner87 commented
Thx

2024-11-22 07:38 UTC, ReneWerner87 approved these changes

2024-11-22 07:47 UTC, ReneWerner87 commented
@ItsMeSamey pls fix the lint errors 

![image](https://github.com/user-attachments/assets/c0f4fbfd-11d9-42bf-a140-01b91af470a6)

2024-11-24 18:18 UTC, ItsMeSamey commented
@gaby
I believe this is ready to be merged now

2024-11-25 03:50 UTC, gaby approved these changes
👍 LGTM

2024-11-25 03:51 UTC, gaby commented
@ReneWerner87 @efectn Please check my changes to the README.md, if all good then we can merge it.

2024-11-25 10:51 UTC, merged