🐛 fix: Improve naming convention for Context related functions
gofiber/fiber pull request #3193
Opened 2024-11-07 14:50 UTC by gaby

# Description

- The standard practice in golang is to have a function named `Context()` that returns the `context.Context`. In Fiber's case this function was named `UserContext()` which is confusing to users. This PR renames `UserContext()` to `Context()`.
- At the same time we were using `Context()` for returning the FastHTTP `RequestCtx` object. This function has been renamed `RequestCtx()`.

Fixes #3186 

## Changes introduced
- [x] Documentation Update: Detail the updates made to the documentation and links to the changed files.
- [x] API Longevity: Discuss the steps taken to ensure that the new or updated APIs are consistent and not prone to breaking changes.

## Type of change
- [x] Documentation update (changes to documentation)
- [x] Code consistency (non-breaking change which improves code reliability and robustness)

2024-11-08 04:10 UTC, gaby commented on middleware/cache/cache_test.go
> +		path := c.RequestCtx().URI().LastPathSegment()
We are renaming Context() to RequestCtx() and UserContext() to Context()

2024-11-10 23:43 UTC, gaby commented on middleware/adaptor/adaptor.go
> +			CopyContextToFiberContext(r.Context(), c.RequestCtx())
I didn't change the left side. The left side is the net/http context.Context object. The one on the right side is the fasthttp RequestCtx

2024-11-11 09:39 UTC, ReneWerner87 commented on docs/api/ctx.md
> +## Context
Don´t forget the documentation for the fasthttp context

2024-11-11 09:39 UTC, ReneWerner87 commented on docs/api/ctx.md
> +## SetContext
pls add these changes to the "what´s new" section

2024-11-11 09:40 UTC, ReneWerner87 requested changes
LGTM, only some minor stuff (markdown documentation)

2024-11-12 01:53 UTC, gaby commented
Updating docs in a few minutes.

2024-11-12 02:13 UTC, gaby commented
@ReneWerner87 Done

2024-11-12 05:50 UTC, JIeJaitt commented
@gaby This PR will be merged in v3. By the way, when will the v3 version be released?

2024-11-12 06:41 UTC, JIeJaitt commented
![image](https://github.com/user-attachments/assets/4af5f3c9-4181-4fb9-924a-e2d2b990aa45)
Do @gaby need to rename this？

2024-11-12 07:54 UTC, ReneWerner87 approved these changes

2024-11-12 11:24 UTC, gaby commented
@JIeJaitt Yes, PR is v3 related. It's a breaking change. Going from v2 to v3 requires changes, it's a major release thus why we are doing the "What's New" document.

The key can stay named the same since its internal to Fiber.

2024-11-13 13:01 UTC, efectn approved these changes

2024-11-13 15:12 UTC, merged