🔥 feat: Add support to create client from existing client
gofiber/fiber pull request #3214
Opened 2024-11-23 12:16 UTC by mitulagr2

# Description

Add support for passing a custom fasthttp client to the fiber http client, to allow more granular fine tuning by the users.

Fixes #3107 

## Type of change

- [x] New feature (non-breaking change which adds functionality)
  - Add `NewWithClient` method to client.
- [x] Documentation update (changes to documentation)
  - Add method to [client docs](https://github.com/gofiber/fiber/blob/main/docs/client/rest.md#usage).
- [x] Code consistency (non-breaking change which improves code reliability and robustness)
  - The `New` method calls `NewWithClient` internally.

2024-11-23 12:25 UTC, gaby requested changes

2024-11-23 12:25 UTC, gaby commented on client/client.go
> +// NewWithClient creates and returns a new Client object from an eisting client object.
Typo "existing"

2024-11-23 12:25 UTC, gaby commented on client/client.go
> +func NewWithClient(c *fasthttp.Client) *Client {
We need a unit-test for this function.

2024-11-23 12:25 UTC, gaby commented on client/client.go
> +// NewWithClient creates and returns a new Client object from an eisting client object.
Remove redundant "object" at the end of sentence.

2024-11-23 12:31 UTC, mitulagr2 commented on client/client.go
> +func NewWithClient(c *fasthttp.Client) *Client {
On it!

2024-11-23 17:25 UTC, gaby requested changes

2024-11-23 17:25 UTC, gaby commented on client/client.go
> +func NewWithClient(c *fasthttp.Client) *Client {
@mitulagr2 Can you add the nil check suggested including the panic.

2024-11-23 17:27 UTC, gaby commented on client/client.go
> +func NewWithClient(c *fasthttp.Client) *Client {
Also add a test where you call the function with `nil`, and test that it panics. We use testify you can check this with:

```go
require.Panics(t, func(){
    // create client with nil here to throw panic
})
```

2024-11-23 18:03 UTC, gaby approved these changes
👍 LGTM

2024-11-23 19:30 UTC, efectn approved these changes

2024-11-25 10:53 UTC, ReneWerner87 approved these changes

2024-11-25 10:54 UTC, merged